export const DECKS = [
  {
    id: 'pdf',
    name: 'PDF Deck',
    color: '#C0392B',
    tools: [
      {
        slug: 'pdf-to-word',
        name: 'PDF to Word',
        icon: '📄',
        desc: 'Convert PDF to editable DOCX, layout preserved.',
        accept: '.pdf',
        kind: 'convert',
        seoTitle: 'Convert PDF to Word Free Online | Layout Preserved — PDFDeck',
        seoDesc: 'Convert PDF to editable Word documents online for free. Preserves layout and formatting. No sign up needed. Files deleted immediately after conversion.',
        related: ['word-to-pdf', 'compress-pdf'],
        faq: [
          { q: 'Is PDF to Word conversion free?', a: 'Yes, completely free. No account required and no watermarks added to your file.' },
          { q: 'Will my formatting be preserved?', a: 'Layout and text formatting are preserved as closely as possible. Complex multi-column PDFs may need minor touch-ups in Word after conversion.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result. Nothing is ever written to disk or retained.' },
        ],
      },
      {
        slug: 'word-to-pdf',
        name: 'Word to PDF',
        icon: '📝',
        desc: 'Turn DOC or DOCX into a clean PDF.',
        accept: '.doc,.docx',
        kind: 'convert',
        seoTitle: 'Convert Word to PDF Free Online | DOC & DOCX — PDFDeck',
        seoDesc: 'Convert Word documents to PDF online for free. Keeps your formatting intact. No software to install. No sign up. Files deleted immediately.',
        related: ['pdf-to-word', 'merge-pdf'],
        faq: [
          { q: 'Is Word to PDF conversion free?', a: 'Yes. No account or software installation needed. Upload your file and download the PDF.' },
          { q: 'What Word formats are supported?', a: 'Both DOC and DOCX files are accepted.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'compress-pdf',
        name: 'Compress PDF',
        icon: '🗜️',
        desc: 'Shrink file size without visible quality loss.',
        accept: '.pdf',
        kind: 'compress',
        seoTitle: 'Compress PDF | Reduce File Size Free Online — PDFDeck',
        seoDesc: 'Compress PDF files online for free. Reduce file size without visible quality loss. No sign up needed. Files deleted immediately after processing.',
        related: ['merge-pdf', 'split-pdf'],
        faq: [
          { q: 'How much will my PDF shrink?', a: 'Compression rates vary by content. PDFs with many images typically compress by 50 to 80 percent. Text-only PDFs compress less.' },
          { q: 'Will compression reduce quality?', a: 'The tool targets file size reduction with minimal visible quality loss. Images are optimized rather than removed.' },
          { q: 'Are my files stored after processing?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'merge-pdf',
        name: 'Merge PDF',
        icon: '🧩',
        desc: 'Combine multiple PDFs in the order you choose.',
        accept: '.pdf',
        kind: 'merge',
        multi: true,
        seoTitle: 'Merge PDF Files Free Online | No Sign Up — PDFDeck',
        seoDesc: 'Merge multiple PDF files into one online for free. Drag to reorder, download instantly. No sign up. Files deleted immediately.',
        related: ['split-pdf', 'compress-pdf'],
        faq: [
          { q: 'How many PDFs can I merge at once?', a: 'You can merge as many PDFs as you need in a single job. Add them in any order before combining.' },
          { q: 'Is merging PDFs free?', a: 'Yes. No account required. Upload your files and download the merged result immediately.' },
          { q: 'Are my files stored after merging?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'split-pdf',
        name: 'Split PDF',
        icon: '✂️',
        desc: 'Extract pages or split into separate files.',
        accept: '.pdf',
        kind: 'split',
        seoTitle: 'Split PDF | Extract Pages Free Online — PDFDeck',
        seoDesc: 'Split PDF files into separate pages or extract a page range online for free. No sign up. Files deleted immediately after processing.',
        related: ['merge-pdf', 'pdf-to-jpg'],
        faq: [
          { q: 'How do I specify which pages to extract?', a: 'Enter a range like 1-3, individual pages like 1, 4, 7, or combine them: 1-3, 5, 8-10.' },
          { q: 'Is splitting PDFs free?', a: 'Yes. No account needed. Enter your page range and download the extracted pages instantly.' },
          { q: 'Are my files stored after splitting?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'pdf-to-jpg',
        name: 'PDF to JPG',
        icon: '🖼️',
        desc: 'Save each PDF page as a high-quality image.',
        accept: '.pdf',
        kind: 'convert',
        seoTitle: 'PDF to JPG | Convert PDF Pages to Images Free — PDFDeck',
        seoDesc: 'Convert PDF pages to high-quality JPG images online for free. Download all pages instantly. No sign up. Files deleted immediately.',
        related: ['jpg-to-pdf', 'split-pdf'],
        faq: [
          { q: 'What resolution are the output images?', a: 'Pages are exported at high resolution. Quality is suitable for screen use and most print needs.' },
          { q: 'Is PDF to JPG conversion free?', a: 'Yes. No account needed. Each page of your PDF is exported as a separate JPG image.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'jpg-to-pdf',
        name: 'JPG to PDF',
        icon: '📑',
        desc: 'Combine images into a single PDF.',
        accept: '.jpg,.jpeg,.png',
        kind: 'convert',
        multi: true,
        seoTitle: 'JPG to PDF | Convert Images to PDF Free Online — PDFDeck',
        seoDesc: 'Convert JPG images to PDF online for free. Combine multiple photos into one PDF document. No sign up. Files deleted immediately.',
        related: ['pdf-to-jpg', 'image-to-pdf'],
        faq: [
          { q: 'Can I combine multiple images into one PDF?', a: 'Yes. Upload multiple images at once and they will all be combined into a single PDF in the order you add them.' },
          { q: 'Which image formats are accepted?', a: 'JPG, JPEG, and PNG files are all accepted.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'pdf-to-excel',
        name: 'PDF to Excel',
        icon: '📊',
        desc: 'Pull tables out of PDFs into editable XLSX.',
        accept: '.pdf',
        kind: 'convert',
        seoTitle: 'PDF to Excel | Extract Tables to XLSX Free Online — PDFDeck',
        seoDesc: 'Convert PDF tables to editable Excel spreadsheets online for free. Pull data out of any PDF into XLSX. No sign up. Files deleted immediately.',
        related: ['extract-data', 'pdf-to-word'],
        faq: [
          { q: 'How accurate is the table extraction?', a: 'Accuracy is highest for digitally created PDFs with clean table layouts. Scanned PDFs may benefit from running OCR first.' },
          { q: 'Is PDF to Excel conversion free?', a: 'Yes. No account needed. Tables are extracted and delivered as an XLSX file.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
    ],
  },
  {
    id: 'image',
    name: 'Image Deck',
    color: '#1A5FBF',
    tools: [
      {
        slug: 'image-converter',
        name: 'Image Converter',
        icon: '🔄',
        desc: 'Convert between PNG, JPG, WebP, HEIC, and AVIF.',
        accept: 'image/*',
        kind: 'convert',
        seoTitle: 'Image Converter | Convert PNG, JPG, WebP, HEIC Free — PDFDeck',
        seoDesc: 'Convert images between PNG, JPG, WebP, HEIC, and AVIF online for free. Fast and free. No sign up. Files deleted immediately.',
        related: ['compress-image', 'resize-image'],
        faq: [
          { q: 'Which image formats are supported?', a: 'PNG, JPG, WebP, HEIC, and AVIF. Convert from any of these formats to any other.' },
          { q: 'Is image conversion free?', a: 'Yes. No account or installation needed. Choose your output format and download the converted image.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'compress-image',
        name: 'Compress Image',
        icon: '📉',
        desc: 'Smaller files, same look. Tuned per image.',
        accept: 'image/*',
        kind: 'compress',
        multi: true,
        seoTitle: 'Compress Image | Reduce Image File Size Free Online — PDFDeck',
        seoDesc: 'Compress images online for free. Reduce file size without visible quality loss. Supports JPG, PNG, and WebP. No sign up. Files deleted immediately.',
        related: ['resize-image', 'image-converter'],
        faq: [
          { q: 'Will compressing reduce visible quality?', a: 'The tool is tuned to minimize file size with minimal visible quality loss. Compression settings are optimized per image type.' },
          { q: 'Is image compression free?', a: 'Yes. You can compress multiple images at once. No account required.' },
          { q: 'Are my files stored after compression?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'resize-image',
        name: 'Resize Image',
        icon: '📐',
        desc: 'Exact dimensions or scale by percentage.',
        accept: 'image/*',
        kind: 'edit',
        seoTitle: 'Resize Image | Change Dimensions Free Online — PDFDeck',
        seoDesc: 'Resize images to exact dimensions or scale by percentage online for free. Supports JPG, PNG, WebP. No sign up. Files deleted immediately.',
        related: ['compress-image', 'image-to-pdf'],
        faq: [
          { q: 'Can I scale an image proportionally?', a: 'Yes. Leave one dimension blank and the image scales proportionally to match the dimension you set.' },
          { q: 'Is image resizing free?', a: 'Yes. Enter your target dimensions and download the resized image instantly. No account needed.' },
          { q: 'Are my files stored after resizing?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
      {
        slug: 'image-to-pdf',
        name: 'Image to PDF',
        icon: '🗂️',
        desc: 'Turn photos and scans into a tidy PDF.',
        accept: 'image/*',
        kind: 'convert',
        multi: true,
        seoTitle: 'Image to PDF | Convert Photos & Scans to PDF Free — PDFDeck',
        seoDesc: 'Convert images to PDF online for free. Turn photos, scans, and screenshots into a single PDF document. No sign up. Files deleted immediately.',
        related: ['jpg-to-pdf', 'compress-pdf'],
        faq: [
          { q: 'How many images can I convert at once?', a: 'Multiple images are accepted and combined into a single PDF in the order you add them.' },
          { q: 'Which image formats are supported?', a: 'Any common image format including JPG, PNG, WebP, and HEIC.' },
          { q: 'Are my files stored after conversion?', a: 'No. Files are processed in memory and deleted immediately once you download your result.' },
        ],
      },
    ],
  },
  {
    id: 'ai',
    name: 'AI Deck',
    color: '#0D7377',
    ai: true,
    tools: [
      {
        slug: 'summarize-pdf',
        name: 'Summarize PDF',
        icon: '✨',
        desc: 'Key points from any document in seconds.',
        accept: '.pdf',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'Summarize PDF with AI | Key Points in Seconds — PDFDeck',
        seoDesc: 'Summarize any PDF document with AI. Get key points, insights, and takeaways in seconds. No sign up. Files deleted immediately after processing.',
        related: ['chat-with-pdf', 'extract-data'],
        faq: [
          { q: 'How long does summarization take?', a: 'Most documents are summarized in under 30 seconds. The AI reads the full document before generating a summary.' },
          { q: 'What kinds of documents work best?', a: 'Reports, research papers, contracts, and articles all summarize well. The AI handles both short and long documents.' },
          { q: 'Are my files stored after processing?', a: 'No. Files are processed in memory and deleted immediately after your session ends.' },
        ],
      },
      {
        slug: 'chat-with-pdf',
        name: 'Chat with PDF',
        icon: '💬',
        desc: 'Ask your document questions, get cited answers.',
        accept: '.pdf',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'Chat with PDF | Ask Your Document Questions with AI — PDFDeck',
        seoDesc: 'Chat with any PDF using AI. Ask questions and get accurate, cited answers. Understand documents faster. Files deleted immediately after your session.',
        related: ['summarize-pdf', 'ocr-pdf'],
        faq: [
          { q: 'How accurate are the answers?', a: 'Answers are generated directly from the document content. The AI cites the relevant section so you can verify the source.' },
          { q: 'What kinds of questions can I ask?', a: 'Any question about the document content. Factual lookups, comparisons, summaries of specific sections, and clarifications all work well.' },
          { q: 'Are my files stored after processing?', a: 'No. Files are processed in memory and deleted immediately after your session ends.' },
        ],
      },
      {
        slug: 'extract-data',
        name: 'Extract Data',
        icon: '🧾',
        desc: 'Invoices and tables out of PDFs, into CSV.',
        accept: '.pdf',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'Extract Data from PDF | AI Invoice & Table Extraction — PDFDeck',
        seoDesc: 'Extract tables and data from PDF invoices and documents using AI. Get structured results as CSV. No sign up. Files deleted immediately.',
        related: ['ocr-pdf', 'pdf-to-excel'],
        faq: [
          { q: 'What kinds of data can it extract?', a: 'Invoices, tables, line items, and structured data from any PDF. Output is delivered as a CSV ready to open in Excel or Google Sheets.' },
          { q: 'Does it work on scanned invoices?', a: 'Yes. The AI can read scanned documents, though clarity of the scan affects accuracy.' },
          { q: 'Are my files stored after processing?', a: 'No. Files are processed in memory and deleted immediately after your session ends.' },
        ],
      },
      {
        slug: 'ocr-pdf',
        name: 'OCR PDF',
        icon: '🔍',
        desc: 'Extract all text from scanned PDFs and images.',
        accept: '.pdf,image/*',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'OCR PDF | Extract Text from Scanned PDFs Free — PDFDeck',
        seoDesc: 'Extract text from scanned PDFs and images using OCR. Works on any scanned document or photo. No sign up. Files deleted immediately after processing.',
        related: ['extract-data', 'pdf-to-word'],
        faq: [
          { q: 'What if my scan is low quality?', a: 'OCR works best on clear, well-lit scans. Very faint text or low-resolution images may produce incomplete results.' },
          { q: 'Does it work on images as well as PDFs?', a: 'Yes. Both scanned PDF files and image files (JPG, PNG, etc.) are accepted.' },
          { q: 'Are my files stored after processing?', a: 'No. Files are processed in memory and deleted immediately after your session ends.' },
        ],
      },
    ],
  },
]

export const ALL_TOOLS = DECKS.flatMap(d => d.tools)
export const findTool = slug => ALL_TOOLS.find(t => t.slug === slug)
export const toolHref = tool => `/${tool.slug}`
export const DECK_COLORS = Object.fromEntries(DECKS.map(d => [d.id, d.color]))
