export const DECKS = [
  {
    id: 'pdf',
    name: 'PDF Deck',
    color: '#C0392B',
    tools: [
      {
        slug: 'pdf-to-word',
        name: 'PDF to Word',
        icon: '📄',
        desc: 'Convert PDF to editable DOCX, layout preserved.',
        accept: '.pdf',
        kind: 'convert',
        seoTitle: 'Convert PDF to Word Free Online | Layout Preserved — PDF Deck',
        seoDesc: 'Convert PDF to editable Word documents online for free. Preserves layout and formatting. No sign up needed. Files deleted immediately after conversion.',
      },
      {
        slug: 'word-to-pdf',
        name: 'Word to PDF',
        icon: '📝',
        desc: 'Turn DOC or DOCX into a clean PDF.',
        accept: '.doc,.docx',
        kind: 'convert',
        seoTitle: 'Convert Word to PDF Free Online | DOC & DOCX — PDF Deck',
        seoDesc: 'Convert Word documents to PDF online for free. Keeps your formatting intact. No software to install. No sign up. Files deleted immediately.',
      },
      {
        slug: 'compress-pdf',
        name: 'Compress PDF',
        icon: '🗜️',
        desc: 'Shrink file size without visible quality loss.',
        accept: '.pdf',
        kind: 'compress',
        seoTitle: 'Compress PDF | Reduce File Size Free Online — PDF Deck',
        seoDesc: 'Compress PDF files online for free. Reduce file size without visible quality loss. No sign up needed. Files deleted immediately after processing.',
      },
      {
        slug: 'merge-pdf',
        name: 'Merge PDF',
        icon: '🧩',
        desc: 'Combine multiple PDFs in the order you choose.',
        accept: '.pdf',
        kind: 'merge',
        multi: true,
        seoTitle: 'Merge PDF Files Free Online | No Sign Up — PDF Deck',
        seoDesc: 'Merge multiple PDF files into one online for free. Drag to reorder, download instantly. No sign up. Files deleted immediately.',
      },
      {
        slug: 'split-pdf',
        name: 'Split PDF',
        icon: '✂️',
        desc: 'Extract pages or split into separate files.',
        accept: '.pdf',
        kind: 'split',
        seoTitle: 'Split PDF | Extract Pages Free Online — PDF Deck',
        seoDesc: 'Split PDF files into separate pages or extract a page range online for free. No sign up. Files deleted immediately after processing.',
      },
      {
        slug: 'pdf-to-jpg',
        name: 'PDF to JPG',
        icon: '🖼️',
        desc: 'Save each PDF page as a high-quality image.',
        accept: '.pdf',
        kind: 'convert',
        seoTitle: 'PDF to JPG | Convert PDF Pages to Images Free — PDF Deck',
        seoDesc: 'Convert PDF pages to high-quality JPG images online for free. Download all pages instantly. No sign up. Files deleted immediately.',
      },
      {
        slug: 'jpg-to-pdf',
        name: 'JPG to PDF',
        icon: '📑',
        desc: 'Combine images into a single PDF.',
        accept: '.jpg,.jpeg,.png',
        kind: 'convert',
        multi: true,
        seoTitle: 'JPG to PDF | Convert Images to PDF Free Online — PDF Deck',
        seoDesc: 'Convert JPG images to PDF online for free. Combine multiple photos into one PDF document. No sign up. Files deleted immediately.',
      },
      {
        slug: 'pdf-to-excel',
        name: 'PDF to Excel',
        icon: '📊',
        desc: 'Pull tables out of PDFs into editable XLSX.',
        accept: '.pdf',
        kind: 'convert',
        seoTitle: 'PDF to Excel | Extract Tables to XLSX Free Online — PDF Deck',
        seoDesc: 'Convert PDF tables to editable Excel spreadsheets online for free. Pull data out of any PDF into XLSX. No sign up. Files deleted immediately.',
      },
    ],
  },
  {
    id: 'image',
    name: 'Image Deck',
    color: '#1A5FBF',
    tools: [
      {
        slug: 'image-converter',
        name: 'Image Converter',
        icon: '🔄',
        desc: 'Convert between PNG, JPG, WebP, HEIC, and AVIF.',
        accept: 'image/*',
        kind: 'convert',
        seoTitle: 'Image Converter | Convert PNG, JPG, WebP, HEIC Free — PDF Deck',
        seoDesc: 'Convert images between PNG, JPG, WebP, HEIC, and AVIF online for free. Fast and free. No sign up. Files deleted immediately.',
      },
      {
        slug: 'compress-image',
        name: 'Compress Image',
        icon: '📉',
        desc: 'Smaller files, same look. Tuned per image.',
        accept: 'image/*',
        kind: 'compress',
        multi: true,
        seoTitle: 'Compress Image | Reduce Image File Size Free Online — PDF Deck',
        seoDesc: 'Compress images online for free. Reduce file size without visible quality loss. Supports JPG, PNG, and WebP. No sign up. Files deleted immediately.',
      },
      {
        slug: 'resize-image',
        name: 'Resize Image',
        icon: '📐',
        desc: 'Exact dimensions or scale by percentage.',
        accept: 'image/*',
        kind: 'edit',
        seoTitle: 'Resize Image | Change Dimensions Free Online — PDF Deck',
        seoDesc: 'Resize images to exact dimensions or scale by percentage online for free. Supports JPG, PNG, WebP. No sign up. Files deleted immediately.',
      },
      {
        slug: 'image-to-pdf',
        name: 'Image to PDF',
        icon: '🗂️',
        desc: 'Turn photos and scans into a tidy PDF.',
        accept: 'image/*',
        kind: 'convert',
        multi: true,
        seoTitle: 'Image to PDF | Convert Photos & Scans to PDF Free — PDF Deck',
        seoDesc: 'Convert images to PDF online for free. Turn photos, scans, and screenshots into a single PDF document. No sign up. Files deleted immediately.',
      },
    ],
  },
  {
    id: 'ai',
    name: 'AI Deck',
    color: '#0D7377',
    ai: true,
    tools: [
      {
        slug: 'summarize-pdf',
        name: 'Summarize PDF',
        icon: '✨',
        desc: 'Key points from any document in seconds.',
        accept: '.pdf',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'Summarize PDF with AI | Key Points in Seconds — PDF Deck',
        seoDesc: 'Summarize any PDF document with AI. Get key points, insights, and takeaways in seconds. No sign up. Files deleted immediately after processing.',
      },
      {
        slug: 'chat-with-pdf',
        name: 'Chat with PDF',
        icon: '💬',
        desc: 'Ask your document questions, get cited answers.',
        accept: '.pdf',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'Chat with PDF | Ask Your Document Questions with AI — PDF Deck',
        seoDesc: 'Chat with any PDF using AI. Ask questions and get accurate, cited answers. Understand documents faster. Files deleted immediately after your session.',
      },
      {
        slug: 'extract-data',
        name: 'Extract Data',
        icon: '🧾',
        desc: 'Invoices and tables out of PDFs, into CSV.',
        accept: '.pdf',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'Extract Data from PDF | AI Invoice & Table Extraction — PDF Deck',
        seoDesc: 'Extract tables and data from PDF invoices and documents using AI. Get structured results as CSV. No sign up. Files deleted immediately.',
      },
      {
        slug: 'ocr-pdf',
        name: 'OCR PDF',
        icon: '🔍',
        desc: 'Extract all text from scanned PDFs and images.',
        accept: '.pdf,image/*',
        kind: 'ai',
        ai: true,
        pro: true,
        seoTitle: 'OCR PDF | Extract Text from Scanned PDFs Free — PDF Deck',
        seoDesc: 'Extract text from scanned PDFs and images using OCR. Works on any scanned document or photo. No sign up. Files deleted immediately after processing.',
      },
    ],
  },
]

export const ALL_TOOLS = DECKS.flatMap(d => d.tools)
export const findTool = slug => ALL_TOOLS.find(t => t.slug === slug)
export const toolHref = tool => `/${tool.slug}`
export const DECK_COLORS = Object.fromEntries(DECKS.map(d => [d.id, d.color]))
